name: flutter_final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_id: ^0.3.6
  device_info_plus: ^9.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  uuid: ^4.5.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#E3F2FD"
  image: assets/images/app_splash.png
  android_12:
    image: assets/images/splash.png
